### ISSUE TITLE
Pre-compiled SIS packages

### ISSUE THREAD

**Issue by deuill** [marknotgeorge/BelleChat#12]
I realize this is approximately 3 years late, and as such not likely to happen, but would it be possible to upload a pre-compiled SIS version of the latest version, if of course you still have one on hand (or can compile one with little hassle)?

This is by far the best IRC client for Symbian, and is very useful for connecting to unsupported services such as Skype/Facebook Messenger/WhatsApp (soon enough, anyways) via things like Bitlbee.

Running Bitlbee over an insecure transport is not recommended, and from what I can tell only version 1.2.900 comes with SSL support, and the only packaged version I've been able to find in the wild is the Nokia Store 1.2 version. Helping out would be very much appreciated!

**Comment by deuill** [comment]
I built a version of Bellechat 1.2.900 and libcommuni 1.0.0 which seems to work (apart from a few random quirks). Uploading this here, although it's obviously not signed or anything so YMMV.

[BelleChat.zip](https://github.com/marknotgeorge/BelleChat/files/242172/BelleChat.zip)

**Comment by marknotgeorge** [comment]
Thanks for posting the precompiled version. I no longer have any Symbian development tools on my system.
